name: Access GitHub Environment Variables

on:
  push:
    branches:
      - main
      - qa
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/qa' && 'qa' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print the selected environment
        run: echo "Selected environment ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/qa' && 'qa' || 'dev' }}"

      - name: Print environment variable from selected environment
        run: echo "The environment variable from the selected environment is ${{ vars.ENV_VALUE }}"
