name: Access GitHub Environment Variables

on:
  push:
    branches:
      - main
      - qa
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment based on branch
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV

      - name: Print the selected environment
        run: echo "Selected environment ${{ env.ENVIRONMENT }}"

      - name: Print environment variable from selected environment
        env:
          ENV_VALUE: ${{ env.ENV_VALUE }}
        run: echo "The environment variable from the selected environment is $ENV_VALUE"
